import fs from "node:fs";
import path from "node:path";
import * as ts from "typescript";
import { collectScriptClasses } from "./script-class.ts";

export const GENERATED_LOGIC_GLOBALS_FILE = "tsw.generated.ts";
const LEGACY_GENERATED_LOGIC_GLOBALS_FILE = ".generated.ts";
const GENERATED_HEADER = "// <auto-generated by tsw>";

function isGeneratedFile(fileName: string): boolean {
    return path.basename(fileName) === GENERATED_LOGIC_GLOBALS_FILE;
}

function renderGeneratedLogicGlobals(classNames: Iterable<string>): string {
    const declarations = [...classNames]
        .sort((a, b) => a.localeCompare(b))
        .map((className) => `declare const _${className}: ${className};`);

    return [
        GENERATED_HEADER,
        "// Provides typed MSW Logic globals for TypeScript code.",
        ...declarations,
        "",
    ].join("\n");
}

function writeIfChanged(filePath: string, contents: string): void {
    if (
        fs.existsSync(filePath) &&
        fs.readFileSync(filePath, "utf8") === contents
    ) {
        return;
    }
    fs.writeFileSync(filePath, contents);
}

export function collectLogicClassNames(program: ts.Program): Set<string> {
    const classNames = new Set<string>();
    for (const sourceFile of program.getSourceFiles()) {
        if (
            sourceFile.isDeclarationFile ||
            isGeneratedFile(sourceFile.fileName)
        ) {
            continue;
        }

        const { infos } = collectScriptClasses(sourceFile);
        for (const info of infos) {
            if (info.scriptType === "Logic") {
                classNames.add(info.className);
            }
        }
    }
    return classNames;
}

export function writeGeneratedLogicGlobals(
    scriptDir: string,
    classNames: Iterable<string>,
): string {
    removeLegacyGeneratedFile(scriptDir);
    const filePath = path.join(scriptDir, GENERATED_LOGIC_GLOBALS_FILE);
    writeIfChanged(filePath, renderGeneratedLogicGlobals(classNames));
    return filePath;
}

function removeLegacyGeneratedFile(scriptDir: string): void {
    const legacyPath = path.join(
        scriptDir,
        LEGACY_GENERATED_LOGIC_GLOBALS_FILE,
    );
    if (
        fs.existsSync(legacyPath) &&
        fs.readFileSync(legacyPath, "utf8").startsWith(GENERATED_HEADER)
    ) {
        fs.unlinkSync(legacyPath);
    }
}

export function updateGeneratedLogicGlobalsFromProgram(
    scriptDir: string,
    program: ts.Program,
): string {
    return writeGeneratedLogicGlobals(
        scriptDir,
        collectLogicClassNames(program),
    );
}

export function updateGeneratedLogicGlobalsFromTsconfig(
    scriptDir: string,
    tsconfigPath: string,
): string {
    const config = ts.readConfigFile(tsconfigPath, ts.sys.readFile);
    if (config.error) {
        throw new Error(
            ts.flattenDiagnosticMessageText(config.error.messageText, "\n"),
        );
    }

    const parsed = ts.parseJsonConfigFileContent(
        config.config,
        ts.sys,
        path.dirname(tsconfigPath),
    );
    if (parsed.errors.length > 0) {
        throw new Error(
            parsed.errors
                .map((error) =>
                    ts.flattenDiagnosticMessageText(error.messageText, "\n"),
                )
                .join("\n"),
        );
    }

    const program = ts.createProgram({
        rootNames: parsed.fileNames,
        options: parsed.options,
    });
    return updateGeneratedLogicGlobalsFromProgram(scriptDir, program);
}
